### ISSUE TITLE
ES6 syntax please

### ISSUE THREAD

**Issue by Ryan-ED** [vladmrnv/ExpressSnippet#5]
Hi. 

Total Node and Express newbie here.
Just want to say I love this extension and I plan on using it a lot.

I am learning NodeJS and would like to use ES6 syntax throughout my apps. I was wondering if you would ever consider revamping this extension to use arrow functions, constants, template strings, etc.

I'm sure a lot of people use this extension too and would love it if it had ES6 syntax.

````javascript
const app = require("express")();

app.get("/person/:name", (req, res) => {
    var name = req.params.name;
    res.send(`Hello, my name is ${name}`);
});

app.listen(3000, () => {
    console.log('App listening on port 3000!');
});
````

Thanks!

**Comment by vladmrnv** [comment]
Hey Ryan, That’s a great suggestion but I’m currently out of town, however after I come back I’d be happy to implement the features.

**Comment by vladmrnv** [comment]
Hey @Ryan-ED , @dexfs appears to have submitted a pull request for it, let me know if there are any other updates you want on it. 

Also I pushed the update to the VSCode App store so you should be able to get it soon.

**Comment by Ryan-ED** [comment]
Wow that's awesome! Thanks a ton @vladmrnv and @dexfs
